file:
  client-path: "/file"
  storage-location: "D://ITE_3rd/ite-file/"
  base-uri: http://localhost:${server.port}${file.client-path}/
spring:
  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ite-ecommerce
    username: postgres
    password: khim3811

  application:
    name: ite-ecommerce
server:
  port: 9090
